apiVersion: batch/v1
kind: Job
metadata:
  name: math-job
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command: ['expr', '3', '+', '4']
      restartPolicy: Never