apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  ports:
    - name: nginx-80
      targetPort: 80
      port: 80
    - name: nginx-90
      targetPort: 90
      port: 90
  selector:
    app: nginx