apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx
      image: nginx
      env:
      - name: color
        valueFrom:
          configMapKeyRef:
            name: app-config
            key: color

