apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  ports:
    - targetPort: 80
      port: 80
      nodePort: 30001
  type: LoadBalancer
  selector:
    app: nginx